// LaTeX export. Walks the editor's ProseMirror document (editor.getJSON()) and emits a standalone
// .tex file the writer can typeset themselves — the source-code companion to the finished-PDF export.
//
// Scope: the prose the editor actually produces — paragraphs, headings, bold/italic/underline/strike/
// code, blockquotes, bullet/ordered lists, code blocks, rules. SCAS highlighting is editor-only (a
// decoration, not stored), so it never reaches the document and isn't exported. Math (KaTeX) and
// figures will map to $…$/\includegraphics here when those land. Targets pdfLaTeX with utf8 inputenc
// (handles Latin text + accents); heavy non-Latin scripts may want XeLaTeX — noted in a file comment.

export interface PMNode {
  type: string
  attrs?: Record<string, unknown>
  content?: PMNode[]
  text?: string
  marks?: Array<{ type: string; attrs?: Record<string, unknown> }>
}

// LaTeX special characters → escaped forms. Backslash/tilde/caret can't be a simple prefix-escape.
const SPECIAL: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
}

function escapeText(s: string): string {
  return s.replace(/[\\&%$#_{}~^]/g, (c) => SPECIAL[c])
}

function applyMarks(text: string, marks?: PMNode['marks']): string {
  if (!marks?.length) return text
  let out = text
  for (const m of marks) {
    switch (m.type) {
      case 'bold': case 'strong': out = `\\textbf{${out}}`; break
      case 'italic': case 'em': out = `\\textit{${out}}`; break
      case 'underline': out = `\\underline{${out}}`; break
      case 'strike': out = `\\sout{${out}}`; break
      case 'code': out = `\\texttt{${out}}`; break
      // Unknown marks (e.g. the provenance slot mark) pass through as plain text.
      default: break
    }
  }
  return out
}

function inline(nodes?: PMNode[]): string {
  if (!nodes) return ''
  return nodes
    .map((n) => {
      if (n.type === 'text') return applyMarks(escapeText(n.text ?? ''), n.marks)
      if (n.type === 'hardBreak') return '\\\\\n'
      return inline(n.content)
    })
    .join('')
}

// Plain (escaped) text of a subtree — for environments where marks don't apply (verbatim handled separately).
function plainInline(nodes?: PMNode[]): string {
  if (!nodes) return ''
  return nodes.map((n) => (n.type === 'text' ? escapeText(n.text ?? '') : plainInline(n.content))).join('')
}

const HEADING_CMD = ['section', 'subsection', 'subsubsection', 'paragraph', 'subparagraph']

function listItems(node: PMNode): string {
  return (node.content ?? [])
    .map((li) => {
      // A listItem holds block content (usually paragraphs); join them, nested lists recurse via block().
      const inner = (li.content ?? [])
        .map((child) => (child.type === 'paragraph' ? inline(child.content) : block(child)))
        .join(' ')
        .trim()
      return `  \\item ${inner}\n`
    })
    .join('')
}

function rawText(node: PMNode): string {
  if (node.type === 'text') return node.text ?? ''
  return (node.content ?? []).map(rawText).join('')
}

function block(node: PMNode): string {
  switch (node.type) {
    case 'paragraph': {
      const body = inline(node.content)
      return body.trim() ? body + '\n\n' : '\n'
    }
    case 'heading': {
      const lvl = Math.min(Number(node.attrs?.level ?? 1), HEADING_CMD.length) - 1
      return `\\${HEADING_CMD[Math.max(0, lvl)]}{${inline(node.content)}}\n\n`
    }
    case 'blockquote':
      return `\\begin{quote}\n${(node.content ?? []).map(block).join('')}\\end{quote}\n\n`
    case 'bulletList':
      return `\\begin{itemize}\n${listItems(node)}\\end{itemize}\n\n`
    case 'orderedList':
      return `\\begin{enumerate}\n${listItems(node)}\\end{enumerate}\n\n`
    case 'codeBlock':
      // verbatim takes raw, UNescaped text.
      return `\\begin{verbatim}\n${rawText(node)}\n\\end{verbatim}\n\n`
    case 'horizontalRule':
      return '\\begin{center}\\noindent\\rule{0.5\\textwidth}{0.4pt}\\end{center}\n\n'
    default:
      // Unknown container: recurse so we never silently drop text.
      return (node.content ?? []).map(block).join('')
  }
}

export function documentToLatex(doc: PMNode, title?: string): string {
  const body = (doc.content ?? []).map(block).join('').trimEnd()
  const t = (title ?? '').trim()
  const preamble = [
    '% Generated by Inkwave. Typeset with pdfLaTeX (utf8). For heavy non-Latin scripts, compile with',
    '% XeLaTeX/LuaLaTeX + fontspec. For a Garamond look, add \\usepackage{ebgaramond} (XeLaTeX).',
    '\\documentclass[12pt,a4paper]{article}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage{lmodern}',
    '\\usepackage[margin=1in]{geometry}',
    '\\usepackage[normalem]{ulem}',
    '\\usepackage{hyperref}',
    t ? `\\title{${escapeText(t)}}` : '',
    t ? '\\author{}' : '',
    t ? '\\date{}' : '',
  ].filter(Boolean)
  return (
    preamble.join('\n') +
    '\n\n\\begin{document}\n' +
    (t ? '\\maketitle\n\n' : '') +
    body +
    '\n\n\\end{document}\n'
  )
}

function safeName(title?: string): string {
  return (title ?? 'inkwave').trim().replace(/[^\w.-]+/g, '_').slice(0, 80) || 'inkwave'
}

// Trigger a .tex download of the document.
export function exportLatexDownload(doc: PMNode, title?: string): void {
  const tex = documentToLatex(doc, title)
  const blob = new Blob([tex], { type: 'application/x-tex' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${safeName(title)}.tex`
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}
