// A synthetic demo Piece for `?music=demo`.
//
// SYNTHETIC, ALWAYS, AND NEVER A REAL SCORE. Demo mode puts fixture data on screen, so a fixture
// here would be published the moment anyone opened the flag — which is why no real engraving and
// none of Peter's own material may ever become one. These pages are drawn by the same generator the
// detector is tested against (`fixtures.ts`), so the demo also shows the reflow doing real work on
// input whose ground truth we know.

import { capturePage, type CapturedPage } from './capture'
import { crampedGrandStaves, skewedPhoto, type ScoreTruth } from './fixtures'
import type { GrayImage } from './reflow'
import { newPiece, type Piece } from './types'

/** Rasterise a fixture's luminance buffer to a PNG blob. */
async function grayToBlob(img: GrayImage): Promise<Blob> {
  const canvas = document.createElement('canvas')
  canvas.width = img.width
  canvas.height = img.height
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('no 2d context')
  const id = ctx.createImageData(img.width, img.height)
  for (let p = 0, i = 0; p < img.data.length; p++, i += 4) {
    id.data[i] = id.data[i + 1] = id.data[i + 2] = img.data[p]
    id.data[i + 3] = 255
  }
  ctx.putImageData(id, 0, 0)
  return new Promise<Blob>((res, rej) =>
    canvas.toBlob(b => (b ? res(b) : rej(new Error('toBlob failed'))), 'image/png'),
  )
}

export interface DemoPiece {
  piece: Piece
  captured: CapturedPage[]
  truth: ScoreTruth[]
}

/** Two synthetic pages: a cramped piano score, and a skewed/shadowed photograph of one. */
export async function buildDemoPiece(id: string): Promise<DemoPiece> {
  const sources = [crampedGrandStaves(), skewedPhoto()]
  const captured: CapturedPage[] = []
  for (const s of sources) captured.push(await capturePage(await grayToBlob(s.img)))

  const piece: Piece = {
    ...newPiece({
      id,
      title: 'Demo score (synthetic)',
      source: { type: 'photo', captured_via: 'image' },
    }),
    composer: 'Generated by Inkwave — not a real engraving',
  }
  return { piece, captured, truth: sources.map(s => s.truth) }
}
