// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit. The latin/latin-ext faces root.tsx
// preloads, so the serif body paints without a flash. Re-run the script to refresh.
export const FONT_PRELOAD: string[] = [
  '/fonts/eb-garamond-400-italic-93.woff2',
  '/fonts/eb-garamond-400-italic-94.woff2',
  '/fonts/eb-garamond-500-italic-100.woff2',
  '/fonts/eb-garamond-500-italic-101.woff2',
  '/fonts/eb-garamond-700-italic-107.woff2',
  '/fonts/eb-garamond-700-italic-108.woff2',
  '/fonts/eb-garamond-400-normal-114.woff2',
  '/fonts/eb-garamond-400-normal-115.woff2',
  '/fonts/eb-garamond-500-normal-121.woff2',
  '/fonts/eb-garamond-500-normal-122.woff2',
  '/fonts/eb-garamond-700-normal-128.woff2',
  '/fonts/eb-garamond-700-normal-129.woff2',
  '/fonts/im-fell-dw-pica-400-italic-182.woff2',
  '/fonts/im-fell-dw-pica-400-normal-183.woff2',
]
