// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit. The latin/latin-ext faces root.tsx
// preloads, so the serif body paints without a flash. Re-run the script to refresh.
export const FONT_PRELOAD: string[] = [
  '/fonts/eb-garamond-400-italic-109.woff2',
  '/fonts/eb-garamond-400-italic-110.woff2',
  '/fonts/eb-garamond-500-italic-116.woff2',
  '/fonts/eb-garamond-500-italic-117.woff2',
  '/fonts/eb-garamond-700-italic-123.woff2',
  '/fonts/eb-garamond-700-italic-124.woff2',
  '/fonts/eb-garamond-400-normal-130.woff2',
  '/fonts/eb-garamond-400-normal-131.woff2',
  '/fonts/eb-garamond-500-normal-137.woff2',
  '/fonts/eb-garamond-500-normal-138.woff2',
  '/fonts/eb-garamond-700-normal-144.woff2',
  '/fonts/eb-garamond-700-normal-145.woff2',
  '/fonts/im-fell-dw-pica-400-italic-198.woff2',
  '/fonts/im-fell-dw-pica-400-normal-199.woff2',
]
