// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit. Only the default Latin face is
// preloaded; other weights, styles, alphabets and families load on demand. Re-run to refresh.
export const FONT_PRELOAD: string[] = [
  '/fonts/eb-garamond-400-normal-131.woff2',
]
